import { factions, mobilityType, scopes, sensorTypes, weaponCategories, type Armor, type Cockpit, type FactionKey, type FuelTank, type Generator, type HeatSink, type MissileCounter, type MobilityBase, type MobilitySystemDevice, type NaJammer, type NaMaker, type Rotorcraft, type Sensor, type Spacer, type StabilitySystemDevice, type Weapon, type WeaponMultiAmmo, type WeaponSystemDevice } from "./partTypes";

function getImageName(filename: string, meshType = 'smd') {
  return `image_${filename}_${meshType}.png`
}

export type PartialPart<T> = Partial<T> & {
  name: string,
  imageName: string,
  filename: string,
  faction: FactionKey,
}

export const partsMobilityBase: PartialPart<MobilityBase>[] = [
  {
    name: 'TL-Dhib',
    imageName: getImageName('LG_TL062'),
    filename: 'LG_TL062',
    faction: factions.SK,
    type: mobilityType.Bipedal,
    weight: 1021,
    energyUse: 212,
    durability: 4032,
    defKE: 46,
    defCE: 34,
    load: 4211,
    speed: 61,
    acceleration: 36,
    brakes: 35,
    turningSpeed: 150,
    rotationSpeed: 66,
    shockAbsorption: 175,
    stability: 126,
    comCompatibility: 120,
  },
  {
    name: 'TL-Sal Kar',
    imageName: getImageName('LG_TL061'),
    filename: 'LG_TL061',
    faction: factions.SK,
    type: mobilityType.Bipedal,
  },
  {
    name: 'TL-Kalb',
    imageName: getImageName('LG_TL063'),
    filename: 'LG_TL063',
    faction: factions.SK,
    type: mobilityType.Bipedal,
  },
  {
    name: 'RFZ-TL-2',
    imageName: getImageName('LG_TL061'),
    filename: 'LG_TL061',
    faction: factions.SK,
    type: mobilityType.Bipedal,
  },
  {
    name: 'M03TL Garfield',
    imageName: getImageName('LG_TL001'),
    filename: 'LG_TL001',
    faction: factions.TAK,
    type: mobilityType.Bipedal,
  },
  {
    name: 'M10TL Shaw',
    imageName: getImageName('LG_TL002'),
    filename: 'LG_TL002',
    faction: factions.TAK,
    type: mobilityType.Bipedal,
  },
  {
    name: 'M13TL Scott',
    imageName: getImageName('LG_TL003'),
    filename: 'LG_TL003',
    faction: factions.TAK,
    type: mobilityType.Bipedal,
  },
  {
    name: 'MSK-TL500',
    imageName: getImageName('LG_TL031'),
    filename: 'LG_TL031',
    faction: factions.MSK,
    type: mobilityType.Bipedal,
  },
  {
    name: 'RFZ-TL-1',
    imageName: getImageName('LG_TL031'),
    filename: 'LG_TL031',
    faction: factions.MSK,
    type: mobilityType.Bipedal,
  },
  {
    name: 'MSK-TL501',
    imageName: getImageName('LG_TL032'),
    filename: 'LG_TL032',
    faction: factions.MSK,
    type: mobilityType.Bipedal,
  },
  {
    name: 'RJ-Jamal',
    imageName: getImageName('LG_RJ061'),
    filename: 'LG_RJ061',
    faction: factions.SK,
    type: mobilityType.Inverse,
  },
  {
    name: 'RJ-Naqa',
    imageName: getImageName('LG_RJ062'),
    filename: 'LG_RJ062',
    faction: factions.SK,
    type: mobilityType.Inverse,
  },
  {
    name: 'M08RJ Hancock',
    imageName: getImageName('LG_RJ002'),
    filename: 'LG_RJ002',
    faction: factions.TAK,
    type: mobilityType.Inverse,
  },
  {
    name: 'M17RJ Douglass',
    imageName: getImageName('LG_RJ003'),
    filename: 'LG_RJ003',
    faction: factions.TAK,
    type: mobilityType.Inverse,
  },
  {
    name: 'M01RJ Burns',
    imageName: getImageName('LG_RJ001'),
    filename: 'LG_RJ001',
    faction: factions.TAK,
    type: mobilityType.Inverse,
  },
  {
    name: 'RFZ-RJ-1',
    imageName: getImageName('LG_RJ001'),
    filename: 'LG_RJ001',
    faction: factions.TAK,
    isRaf: true,
    type: mobilityType.Inverse,
  },
  {
    name: 'MSK-RJ400',
    imageName: getImageName('LG_RJ031'),
    filename: 'LG_RJ031',
    faction: factions.MSK,
    type: mobilityType.Inverse,
  },
  {
    name: 'RFZ-RJ-2',
    imageName: getImageName('LG_RJ031'),
    filename: 'LG_RJ031',
    faction: factions.MSK,
    isRaf: true,
    type: mobilityType.Inverse,
  },
  {
    name: 'MSK-RJ401',
    imageName: getImageName('LG_RJ032'),
    filename: 'LG_RJ032',
    faction: factions.MSK,
    type: mobilityType.Inverse,
  },
  {
    name: 'M09ML Dupont',
    imageName: getImageName('LG_ML002'),
    filename: 'LG_ML002',
    faction: factions.TAK,
    type: mobilityType.Multi,
  },
  {
    name: 'ML-Baqara',
    imageName: getImageName('LG_ML062'),
    filename: 'LG_ML062',
    faction: factions.SK,
    type: mobilityType.Multi,
  },
  {
    name: 'ML-Thawr',
    imageName: getImageName('LG_ML061'),
    filename: 'LG_ML061',
    faction: factions.SK,
    type: mobilityType.Multi,
  },
  {
    name: 'M04ML Grant',
    imageName: getImageName('LG_ML001'),
    filename: 'LG_ML001',
    faction: factions.TAK,
    type: mobilityType.Multi,
  },
  {
    name: 'RFZ-ML-1',
    imageName: getImageName('LG_ML001'),
    filename: 'LG_ML001',
    faction: factions.TAK,
    isRaf: true,
    type: mobilityType.Multi,
  },
  {
    name: 'M15ML Sharman',
    imageName: getImageName('LG_ML011'),
    filename: 'LG_ML011',
    faction: factions.TAK,
    type: mobilityType.Multi,
  },
  {
    name: 'MSK-ML211',
    imageName: getImageName('LG_ML042'),
    filename: 'LG_ML042',
    faction: factions.MSK,
    type: mobilityType.Multi,
  },
  {
    name: 'MSK-ML201',
    imageName: getImageName('LG_ML032'),
    filename: 'LG_ML032',
    faction: factions.MSK,
    type: mobilityType.Multi,
  },
  {
    name: 'MSK-ML200',
    imageName: getImageName('LG_ML031'),
    filename: 'LG_ML031',
    faction: factions.MSK,
    type: mobilityType.Multi,
  },
  {
    name: 'MSK-ML210',
    imageName: getImageName('LG_ML041'),
    filename: 'LG_ML041',
    faction: factions.MSK,
    type: mobilityType.Multi,
  },
  {
    name: 'RFZ-ML-2',
    imageName: getImageName('LG_ML031'),
    filename: 'LG_ML031',
    faction: factions.MSK,
    isRaf: true,
    type: mobilityType.Multi,
  },
  {
    name: 'CL-Himar',
    imageName: getImageName('LG_CL061'),
    filename: 'LG_CL061',
    faction: factions.SK,
    type: mobilityType.Treaded,
  },
  {
    name: 'RFZ-CL-2',
    imageName: getImageName('LG_CL061'),
    filename: 'LG_CL061',
    faction: factions.SK,
    isRaf: true,
    type: mobilityType.Treaded,
  },
  {
    name: 'CL-Baghl',
    imageName: getImageName('LG_CL062'),
    filename: 'LG_CL062',
    faction: factions.SK,
    type: mobilityType.Treaded,
  },
  {
    name: 'M07CL Hooker',
    imageName: getImageName('LG_CL002'),
    filename: 'LG_CL002',
    faction: factions.TAK,
    type: mobilityType.Treaded,
  },
  {
    name: 'M05CL Custer',
    imageName: getImageName('LG_CL001'),
    filename: 'LG_CL001',
    faction: factions.TAK,
    type: mobilityType.Treaded,
  },
  {
    name: 'RFZ-CL-1',
    imageName: getImageName('LG_CL001'),
    filename: 'LG_CL001',
    faction: factions.TAK,
    isRaf: true,
    type: mobilityType.Treaded,
  },
  {
    name: 'M14CL Meade',
    imageName: getImageName('LG_CL003'),
    filename: 'LG_CL003',
    faction: factions.TAK,
    type: mobilityType.Treaded,
  },
  {
    name: 'MSK-CL110',
    imageName: getImageName('LG_CL031'),
    filename: 'LG_CL031',
    faction: factions.MSK,
    type: mobilityType.Treaded,
  },
  {
    name: 'RFZ-CL-X',
    imageName: getImageName('LG_CL031'),
    filename: 'LG_CL031',
    faction: factions.MSK,
    isRaf: true,
    type: mobilityType.Treaded,
  },
  {
    name: 'MSK-CL101',
    imageName: getImageName('LG_CL032'),
    filename: 'LG_CL032',
    faction: factions.MSK,
    type: mobilityType.Treaded,
  },
  {
    name: 'MSK-CL100',
    imageName: getImageName('LG_CL033'),
    filename: 'LG_CL033',
    faction: factions.MSK,
    type: mobilityType.Treaded,
  },
  {
    name: 'HL-Ghazal',
    imageName: getImageName('LG_HL061'),
    filename: 'LG_HL061',
    faction: factions.SK,
    type: mobilityType.Hover,
  },
  {
    name: 'RFZ-HL-2',
    imageName: getImageName('LG_HL061'),
    filename: 'LG_HL061',
    faction: factions.SK,
    isRaf: true,
    type: mobilityType.Hover,
  },
  {
    name: 'HL-Namir',
    imageName: getImageName('LG_HL063'),
    filename: 'LG_HL063',
    faction: factions.SK,
    type: mobilityType.Hover,
  },
  {
    name: 'M06HL Cushing',
    imageName: getImageName('LG_HL001'),
    filename: 'LG_HL001',
    faction: factions.TAK,
    type: mobilityType.Hover,
  },
  {
    name: 'HL-Labua',
    imageName: getImageName('LG_HL062'),
    filename: 'LG_HL062',
    faction: factions.SK,
    type: mobilityType.Hover,
  },
  {
    name: 'RFZ-HL-1',
    imageName: getImageName('LG_HL001'),
    filename: 'LG_HL001',
    faction: factions.TAK,
    isRaf: true,
    type: mobilityType.Hover,
  },
  {
    name: 'M12HL Wells',
    imageName: getImageName('LG_HL002'),
    filename: 'LG_HL002',
    faction: factions.TAK,
    type: mobilityType.Hover,
  },
  {
    name: 'MSK-HL601',
    imageName: getImageName('LG_HL032'),
    filename: 'LG_HL032',
    faction: factions.MSK,
    type: mobilityType.Hover,
  },
  {
    name: 'HL-Asad',
    imageName: getImageName('LG_HL064'),
    filename: 'LG_HL064',
    faction: factions.SK,
    type: mobilityType.Hover,
  },
  {
    name: 'MSK-HL600',
    imageName: getImageName('LG_HL031'),
    filename: 'LG_HL031',
    faction: factions.MSK,
    type: mobilityType.Hover,
  },
  {
    name: 'M02WL Grierson',
    imageName: getImageName('LG_WL001'),
    filename: 'LG_WL001',
    faction: factions.TAK,
    type: mobilityType.Wheeled,
  },
  {
    name: 'M11WL Sheridan',
    imageName: getImageName('LG_WL002'),
    filename: 'LG_WL002',
    faction: factions.TAK,
    type: mobilityType.Wheeled,
  },
  {
    name: 'M16WL Meagher',
    imageName: getImageName('LG_WL003'),
    filename: 'LG_WL003',
    faction: factions.TAK,
    type: mobilityType.Wheeled,
  },
  {
    name: 'WL-Hisan',
    imageName: getImageName('LG_WL061'),
    filename: 'LG_WL061',
    faction: factions.SK,
    type: mobilityType.Wheeled,
  },
  {
    name: 'RFZ-WL-1',
    imageName: getImageName('LG_WL001'),
    filename: 'LG_WL001',
    faction: factions.TAK,
    isRaf: true,
    type: mobilityType.Wheeled,
  },
  {
    name: 'RFZ-WL-2',
    imageName: getImageName('LG_WL061'),
    filename: 'LG_WL061',
    faction: factions.SK,
    isRaf: true,
    type: mobilityType.Wheeled,
  },
  {
    name: 'WL-Jawad',
    imageName: getImageName('LG_WL063'),
    filename: 'LG_WL063',
    faction: factions.SK,
    type: mobilityType.Wheeled,
  },
  {
    name: 'WL-Faras',
    imageName: getImageName('LG_WL062'),
    filename: 'LG_WL062',
    faction: factions.SK,
    type: mobilityType.Wheeled,
  },
  {
    name: 'MSK-WL300',
    imageName: getImageName('LG_WL031'),
    filename: 'LG_WL031',
    faction: factions.MSK,
    type: mobilityType.Wheeled,
  },
  {
    name: 'MSk-WL310',
    imageName: getImageName('LG_WL032'),
    filename: 'LG_WL032',
    faction: factions.MSK,
    type: mobilityType.Wheeled,
  }
]

export const partsCockpit: PartialPart<Cockpit>[] = [
  {
    name: "C-Naml",
    imageName: getImageName('CK_CA062'),
    filename: "CK_CA062",
    faction: factions.SK,
    weight: 581,
    energyUse: 57,
    durability: 2836,
    defKE: 40,
    defCE: 38,
    systemSockets: 9,
    internalPower: 256,
    condenserCapacity: 1698,
    condenserRegen: 303,
    partsManagement: 19,
  },
  {
    name: "RFZ-CK-A1",
    imageName: getImageName('CK_CA001'),
    filename: "CK_CA001",
    isRaf: true,
    faction: factions.TAK,
  },
  {
    name: "M02CK Pickett",
    imageName: getImageName('CK_CA001'),
    filename: "CK_CA001",
    faction: factions.TAK,
  },
  {
    name: "RFZ-CK-A3",
    imageName: getImageName('CK_CA061'),
    filename: "CK_CA061",
    faction: factions.SK,
    isRaf: true,
  },
  {
    name: "C-Sal Kar",
    imageName: getImageName('CK_CA061'),
    filename: "CK_CA061",
    faction: factions.SK,
  },
  {
    name: "M07CK Brooke",
    imageName: getImageName('CK_CA002'),
    filename: "CK_CA002",
    faction: factions.TAK,
  },
  {
    name: "C-Dabbur",
    imageName: getImageName('CK_CA063'),
    filename: "CK_CA063",
    faction: factions.SK,
  },
  {
    name: "C-Ankabut",
    imageName: getImageName('CK_CA064'),
    filename: "CK_CA064",
    faction: factions.SK,
  },
  {
    name: "RFZ-CK-A2",
    imageName: getImageName('CK_CA003'),
    filename: "CK_CA003",
    faction: factions.TAK,
    isRaf: true,
  },
  {
    name: "M01CK Forrest",
    imageName: getImageName('CK_CA003'),
    filename: "CK_CA003",
    faction: factions.TAK,
  },
  {
    name: "MSK-C10",
    imageName: getImageName('CK_CA031'),
    filename: "CK_CA031",
    faction: factions.MSK,
  },
  {
    name: "M03CK Jackson",
    imageName: getImageName('CK_CA004'),
    filename: "CK_CA004",
    faction: factions.TAK,
  },
  {
    name: "MSK-C20",
    imageName: getImageName('CK_CA032'),
    filename: "CK_CA032",
    faction: factions.MSK,
  },
  {
    name: "C-Jarad",
    imageName: getImageName('CK_CB062'),
    filename: "CK_CB062",
    faction: factions.SK,
  },
  {
    name: "C-Farasha",
    imageName: getImageName('CK_CB063'),
    filename: "CK_CB063",
    faction: factions.SK,
  },
  {
    name: "M05CK Johnston",
    imageName: getImageName('CK_CB002'),
    filename: "CK_CB002",
    faction: factions.TAK,
  },
  {
    name: "C-Nahl",
    imageName: getImageName('CK_CB061'),
    filename: "CK_CB061",
    faction: factions.SK,
  },
  {
    name: "M04CK Stuart",
    imageName: getImageName('CK_CB001'),
    filename: "CK_CB001",
    faction: factions.TAK,
  },
  {
    name: "M06CK Lee",
    imageName: getImageName('CK_CB003'),
    filename: "CK_CB003",
    faction: factions.TAK,
  },
  {
    name: "RFZ-CK-B1",
    imageName: getImageName('CK_CB031'),
    filename: "CK_CB031",
    faction: factions.MSK,
    isRaf: true,
  },
  {
    name: "MSK-C100",
    imageName: getImageName('CK_CB031'),
    filename: "CK_CB031",
    faction: factions.MSK,
  },
  {
    name: "MSK-C110",
    imageName: getImageName('CK_CB032'),
    filename: "CK_CB032",
    faction: factions.MSK,
  },
  {
    name: "MSK-C1000",
    imageName: getImageName('CK_CC031'),
    filename: "CK_CC031",
    faction: factions.MSK,
  },
  {
    name: "MSK-C1500",
    imageName: getImageName('CK_CC032'),
    filename: "CK_CC032",
    faction: factions.MSK,
  },
  {
    name: "MSK-C1001",
    imageName: getImageName('CK_CC033'),
    filename: "CK_CC033",
    faction: factions.MSK,
  }
];

export const partsMobilitySystemDevice: MobilitySystemDevice[] = [
  {
    name: 'MSK-MC1000',
    imageName: getImageName('CP_MC031'),
    filename: 'CP_MC031',
    socketUse: 2,
    speedEnhancement: 66,
    accelEnhancement: 85,
  },
  {
    name: 'MC-Wahid',
    imageName: getImageName('CP_MC061'),
    filename: 'CP_MC061',
    socketUse: 2,
    speedEnhancement: 90,
    accelEnhancement: 62,
  },
  {
    name: 'RFZ-MC-1',
    imageName: getImageName('CP_MC031'),
    filename: 'CP_MC031',
    socketUse: 2,
    speedEnhancement: 60,
    accelEnhancement: 80,
    isRaf: true,
  },
  {
    name: 'M01MC Russell',
    imageName: getImageName('CP_MC001'),
    filename: 'CP_MC001',
    socketUse: 3,
    speedEnhancement: 128,
    accelEnhancement: 92,
  },
  {
    name: 'MC-Arbaa',
    imageName: getImageName('CP_MC062'),
    filename: 'CP_MC062',
    socketUse: 3,
    speedEnhancement: 97,
    accelEnhancement: 135,
  },
  {
    name: 'RFZ-MC-2',
    imageName: getImageName('CP_MC001'),
    filename: 'CP_MC001',
    socketUse: 3,
    speedEnhancement: 120,
    accelEnhancement: 90,
    isRaf: true,
  },
  {
    name: 'MSK-MC1500',
    imageName: getImageName('CP_MC032'),
    filename: 'CP_MC032',
    socketUse: 4,
    speedEnhancement: 125,
    accelEnhancement: 170,
  },
  {
    name: 'MS-Saba',
    imageName: getImageName('CP_MC063'),
    filename: 'CP_MC063',
    socketUse: 4,
    speedEnhancement: 165,
    accelEnhancement: 130,
  },
  {
    name: 'M02MC Neumann',
    imageName: getImageName('CP_MC002'),
    filename: 'CP_MC002',
    socketUse: 5,
    speedEnhancement: 180,
    accelEnhancement: 150,
  }
];

export const partsWeaponSystemDevice: WeaponSystemDevice[] = [
  {
    name: 'TC-Ithnan',
    imageName: getImageName('CP_AS061'),
    filename: 'CP_AS061',
    socketUse: 1,
    aimStability: 35,
    weaponSystems: 4,
  },
  {
    name: 'M01TC Bardeen',
    imageName: getImageName('CP_AS001'),
    filename: 'CP_AS001',
    socketUse: 2,
    aimStability: 80,
    weaponSystems: 4,
  },
  {
    name: 'MSK-TC1000',
    imageName: getImageName('CP_AS031'),
    filename: 'CP_AS031',
    socketUse: 2,
    aimStability: 100,
    weaponSystems: 3,
  },
  {
    name: 'RFZ-TC-1',
    imageName: getImageName('CP_AS001'),
    filename: 'CP_AS001',
    socketUse: 2,
    aimStability: 70,
    weaponSystems: 4,
    isRaf: true,
  },
  {
    name: 'RFZ-TC-2',
    imageName: getImageName('CP_AS031'),
    filename: 'CP_AS031',
    socketUse: 2,
    aimStability: 80,
    weaponSystems: 3,
    isRaf: true,
  },
  {
    name: 'MSK-TC1500',
    imageName: getImageName('CP_AS032'),
    filename: 'CP_AS032',
    socketUse: 3,
    aimStability: 155,
    weaponSystems: 3,
  },
  {
    name: 'TC-Sitta',
    imageName: getImageName('CP_AS062'),
    filename: 'CP_AS062',
    socketUse: 3,
    aimStability: 200,
    weaponSystems: 2,
  },
  {
    name: 'M02TC Brattain',
    imageName: getImageName('CP_AS002'),
    filename: 'CP_AS002',
    socketUse: 4,
    aimStability: 180,
    weaponSystems: 3,
  },
  {
    name: 'MSK-TC2000',
    imageName: getImageName('CP_AS033'),
    filename: 'CP_AS033',
    socketUse: 5,
    aimStability: 180,
    weaponSystems: 4,
  }
];

export const partsStabilitySystemDevice: StabilitySystemDevice[] = [
  {
    name: 'RC-Khamsa',
    imageName: getImageName('CP_CT062'),
    filename: 'CP_CT062',
    socketUse: 1,
    stabilityBoost: 90,
    rotationBoost: 40,
  },
  {
    name: 'MSK-RC1000',
    imageName: getImageName('CP_CT031'),
    filename: 'CP_CT031',
    socketUse: 2,
    stabilityBoost: 82,
    rotationBoost: 92,
  },
  {
    name: 'RC-Thalatha',
    imageName: getImageName('CP_CT061'),
    filename: 'CP_CT061',
    socketUse: 2,
    stabilityBoost: 105,
    rotationBoost: 84,
  },
  {
    name: 'RFZ-RC-1',
    imageName: getImageName('CP_CT061'),
    filename: 'CP_CT061',
    socketUse: 2,
    stabilityBoost: 85,
    rotationBoost: 70,
    isRaf: true,
  },
  {
    name: 'M01RC Hopper',
    imageName: getImageName('CP_CT001'),
    filename: 'CP_CT001',
    socketUse: 3,
    stabilityBoost: 86,
    rotationBoost: 120,
  },
  {
    name: 'MSK-RC1500',
    imageName: getImageName('CP_CT032'),
    filename: 'CP_CT032',
    socketUse: 3,
    stabilityBoost: 140,
    rotationBoost: 88,
  },
  {
    name: 'RFZ-RC-2',
    imageName: getImageName('CP_CT001'),
    filename: 'CP_CT001',
    socketUse: 3,
    stabilityBoost: 75,
    rotationBoost: 110,
    isRaf: true,
  },
  {
    name: 'M02RC Backus',
    imageName: getImageName('CP_CT002'),
    filename: 'CP_CT002',
    socketUse: 5,
    stabilityBoost: 165,
    rotationBoost: 120,
  },
  {
    name: 'M03RC Mccarthy',
    imageName: getImageName('CP_CT003'),
    filename: 'CP_CT003',
    socketUse: 5,
    stabilityBoost: 105,
    rotationBoost: 185,
  }
];

export const partsGenerator: PartialPart<Generator>[] = [
  {
    name: 'RFZ-GE-A3',
    imageName: getImageName('GE_GA061'),
    filename: 'GE_GA061',
    faction: factions.SK,
    isRaf: true,
  },
  {
    name: 'G-Sal Kar',
    imageName: getImageName('GE_GA061'),
    filename: 'GE_GA061',
    faction: factions.SK,
  },
  {
    name: 'RFZ-GE-A2',
    imageName: getImageName('GE_GA031'),
    filename: 'GE_GA031',
    faction: factions.MSK,
    isRaf: true,
  },
  {
    name: 'MSK-G101',
    imageName: getImageName('GE_GA032'),
    filename: 'GE_GA032',
    faction: factions.MSK,
  },
  {
    name: 'MSK-G100',
    imageName: getImageName('GE_GA031'),
    filename: 'GE_GA031',
    faction: factions.MSK,
  },
  {
    name: 'RFZ-GE-A4',
    imageName: getImageName('GE_GA062'),
    filename: 'GE_GA062',
    faction: factions.SK,
    isRaf: true,
  },
  {
    name: 'M04G Volta',
    imageName: getImageName('GE_GA002'),
    filename: 'GE_GA002',
    faction: factions.TAK,
  },
  {
    name: 'G-Zahara',
    imageName: getImageName('GE_GA062'),
    filename: 'GE_GA062',
    faction: factions.SK,
  },
  {
    name: 'RFZ-GE-A1',
    imageName: getImageName('GE_GA001'),
    filename: 'GE_GA001',
    faction: factions.TAK,
    isRaf: true,
  },
  {
    name: 'M01G Papin',
    imageName: getImageName('GE_GA001'),
    filename: 'GE_GA001',
    faction: factions.TAK,
  },
  {
    name: 'G-Shajar',
    imageName: getImageName('GE_GB061'),
    filename: 'GE_GB061',
    faction: factions.SK,
  },
  {
    name: 'RFZ-GE-B1',
    imageName: getImageName('GE_GB001'),
    filename: 'GE_GB001',
    faction: factions.TAK,
    isRaf: true,
  },
  {
    name: 'M05G Young',
    imageName: getImageName('GE_GB002'),
    filename: 'GE_GB002',
    faction: factions.TAK,
  },
  {
    name: 'M02G Franklin',
    imageName: getImageName('GE_GB001'),
    filename: 'GE_GB001',
    faction: factions.TAK,
  },
  {
    name: 'MSK-G1500',
    imageName: getImageName('GE_GB032'),
    filename: 'GE_GB032',
    faction: factions.MSK,
  },
  {
    name: 'MSK-G1501',
    imageName: getImageName('GE_GB033'),
    filename: 'GE_GB033',
    faction: factions.MSK,
  },
  {
    name: 'RFZ-GE-B2',
    imageName: getImageName('GE_GB031'),
    filename: 'GE_GB031',
    faction: factions.MSK,
    isRaf: true,
  },
  {
    name: 'MSK-G1000',
    imageName: getImageName('GE_GB031'),
    filename: 'GE_GB031',
    faction: factions.MSK,
  },
  {
    name: 'RFZ-GE-C1',
    imageName: getImageName('GE_GC061'),
    filename: 'GE_GC061',
    faction: factions.SK,
    isRaf: true,
  },
  {
    name: 'G-Ushb',
    imageName: getImageName('GE_GC061'),
    filename: 'GE_GC061',
    faction: factions.SK,
  },
  {
    name: 'M06G Nobili',
    imageName: getImageName('GE_GC002'),
    filename: 'GE_GC002',
    faction: factions.TAK,
  },
  {
    name: 'M03G Ampere',
    imageName: getImageName('GE_GC001'),
    filename: 'GE_GC001',
    faction: factions.TAK,
  },
  {
    name: 'G-Saq',
    imageName: getImageName('GE_GC063'),
    filename: 'GE_GC063',
    faction: factions.SK,
  },
  {
    name: 'G-Kala',
    imageName: getImageName('GE_GC062'),
    filename: 'GE_GC062',
    faction: factions.SK,
  },
  {
    name: 'MSK-G10',
    imageName: getImageName('GE_GC031'),
    filename: 'GE_GC031',
    faction: factions.MSK,
  },
]

export const partsSpacer: PartialPart<Spacer>[] = [
  {
    name: 'RFZ-ASP-2',
    imageName: getImageName('AX_SP041'),
    filename: 'AX_SP041',
    faction: factions.MSK,
    isRaf: true,
    weight: 270,
    energyUse: 5,
    durability: 4000,
    defKE: 70,
    defCE: 52,
    connectionPoints: 2,
    shape: "Line"
  },
  {
    name: 'SP-Sadr',
    imageName: getImageName('AX_SP071'),
    filename: 'AX_SP071',
    faction: factions.SK,
  },
  {
    name: 'M02SP Abdomen',
    imageName: getImageName('AX_SP011'),
    filename: 'AX_SP011',
    faction: factions.TAK,
  },
  {
    name: 'MSK-SP100',
    imageName: getImageName('AX_SP041'),
    filename: 'AX_SP041',
    faction: factions.MSK,
  },
  {
    name: 'RFZ-ASP-1',
    imageName: getImageName('AX_SP001'),
    filename: 'AX_SP001',
    faction: factions.TAK,
    isRaf: true,
  },
  {
    name: 'SP-Dhira',
    imageName: getImageName('AX_SP061'),
    filename: 'AX_SP061',
    faction: factions.SK,
  },
  {
    name: 'M01SP Born',
    imageName: getImageName('AX_SP001'),
    filename: 'AX_SP001',
    faction: factions.TAK,
  },
  {
    name: 'MSK-SP200',
    imageName: getImageName('AX_SP031'),
    filename: 'AX_SP031',
    faction: factions.MSK,
  },
  {
    name: 'SP-Rijil',
    imageName: getImageName('AX_SP062'),
    filename: 'AX_SP062',
    faction: factions.SK,
  },
  {
    name: 'M05SP Chest',
    imageName: getImageName('AX_SP002'),
    filename: 'AX_SP002',
    faction: factions.TAK,
  },
  {
    name: 'MSK-SP400',
    imageName: getImageName('AX_SP032'),
    filename: 'AX_SP032',
    faction: factions.MSK,
  },
  {
    name: 'RFZ-ASP-3',
    imageName: getImageName('AX_SP081'),
    filename: 'AX_SP081',
    faction: factions.SK,
    isRaf: true,
  },
  {
    name: 'SP-Yad',
    imageName: getImageName('AX_SP081'),
    filename: 'AX_SP081',
    faction: factions.SK,
  },
  {
    name: 'M03SP Neck',
    imageName: getImageName('AX_SP021'),
    filename: 'AX_SP021',
    faction: factions.TAK,
  },
  {
    name: 'MSK-SP500',
    imageName: getImageName('AX_SP051'),
    filename: 'AX_SP051',
    faction: factions.MSK,
  },
  {
    name: 'SP-Zahr',
    imageName: getImageName('AX_SP072'),
    filename: 'AX_SP072',
    faction: factions.SK,
  },
  {
    name: 'M04SP Finger',
    imageName: getImageName('AX_SP012'),
    filename: 'AX_SP012',
    faction: factions.TAK,
  },
  {
    name: 'MSK-SP300',
    imageName: getImageName('AX_SP042'),
    filename: 'AX_SP042',
    faction: factions.MSK,
  },
  {
    name: 'SP-Isba',
    imageName: getImageName('AX_SP082'),
    filename: 'AX_SP082',
    faction: factions.SK,
  },
  {
    name: 'M06SP Arm',
    imageName: getImageName('AX_SP022'),
    filename: 'AX_SP022',
    faction: factions.TAK,
  },
  {
    name: 'MSK-SP600',
    imageName: getImageName('AX_SP052'),
    filename: 'AX_SP052',
    faction: factions.MSK,
  }
]

export const partsSensor: PartialPart<Sensor>[] = [
  {
    name: 'MSK-SK111',
    imageName: getImageName('AX_SD032'),
    filename: 'AX_SD032',
    faction: factions.MSK,
    weight: 32,
    energyUse: 20,
    durability: 2531,
    defKE: 24,
    defCE: 16,
    type: sensorTypes.NightVision,
    range: 550,
  },
  {
    name: 'RFZ-ASD-N1',
    imageName: getImageName('AX_SD002'),
    filename: 'AX_SD002',
    faction: factions.TAK,
    isRaf: true,
    type: sensorTypes.NightVision,
  },
  {
    name: 'M01SD Huygens',
    imageName: getImageName('AX_SD002'),
    filename: 'AX_SD002',
    faction: factions.TAK,
    type: sensorTypes.NightVision,
  },
  {
    name: 'MSK-SD110',
    imageName: getImageName('AX_SD031'),
    filename: 'AX_SD031',
    faction: factions.MSK,
    type: sensorTypes.NightVision,
  },
  {
    name: 'RFZ-ASD-S1',
    imageName: getImageName('AX_SD033'),
    filename: 'AX_SD033',
    faction: factions.MSK,
    isRaf: true,
    type: sensorTypes.ThermoVision,
  },
  {
    name: 'MSK-SD100',
    imageName: getImageName('AX_SD033'),
    filename: 'AX_SD033',
    faction: factions.MSK,
    type: sensorTypes.ThermoVision,
  },
  {
    name: 'M02SD Faraday',
    imageName: getImageName('AX_SD003'),
    filename: 'AX_SD003',
    faction: factions.TAK,
    type: sensorTypes.ThermoVision,
  },
  {
    name: 'SD-Ayn',
    imageName: getImageName('AX_SD063'),
    filename: 'AX_SD063',
    faction: factions.SK,
    type: sensorTypes.ThermoVision,
  },
  {
    name: 'M03SD Kepler',
    imageName: getImageName('AX_SD001'),
    filename: 'AX_SD001',
    faction: factions.TAK,
    type: sensorTypes.MineDetector,
  },
  {
    name: 'RFZ-ASD-M1',
    imageName: getImageName('AX_SD062'),
    filename: 'AX_SD062',
    faction: factions.SK,
    isRaf: true,
    type: sensorTypes.MineDetector,
  },
  {
    name: 'SD-Udhun',
    imageName: getImageName('AX_SD062'),
    filename: 'AX_SD062',
    faction: factions.SK,
    type: sensorTypes.MineDetector,
  },
  {
    name: 'SD-Anf',
    imageName: getImageName('AX_SD061'),
    filename: 'AX_SD061',
    faction: factions.SK,
    type: sensorTypes.MineDetector,
  }
]

export const partsNaJammer: PartialPart<NaJammer>[] = [
  {
    name: 'JM-Barq',
    imageName: getImageName('AX_JM061'),
    filename: 'AX_JM061',
    faction: factions.SK,
    weight: 135,
    durability: 2034,
    defKE: 30,
    defCE: 26,
    energyUse: 38,
    effectiveTime: 33,
  },
  {
    name: 'RFZ-AJM-1',
    imageName: getImageName('AX_JM001'),
    filename: 'AX_JM001',
    faction: factions.TAK,
    isRaf: true,
  },
  {
    name: 'JM-Saiqa',
    imageName: getImageName('AX_JM062'),
    filename: 'AX_JM062',
    faction: factions.SK,
  },
  {
    name: 'M01JM Sallet',
    imageName: getImageName('AX_JM001'),
    filename: 'AX_JM001',
    faction: factions.TAK,
  },
  {
    name: 'M02JM Basinet',
    imageName: getImageName('AX_JM002'),
    filename: 'AX_JM002',
    faction: factions.TAK,
  },
  {
    name: 'MSK-JM100',
    imageName: getImageName('AX_JM031'),
    filename: 'AX_JM031',
    faction: factions.MSK,
  },
  {
    name: 'JM-Rad',
    imageName: getImageName('AX_JM063'),
    filename: 'AX_JM063',
    faction: factions.SK,
  }
];

export const partsMissileCounter: PartialPart<MissileCounter>[] = [
  {
    name: 'MS-Rih',
    imageName: getImageName('AX_MC061'),
    filename: 'AX_MC061',
    faction: factions.SK,
    weight: 180,
    energyUse: 10,
    durability: 2763,
    defKE: 45,
    defCE: 36,
    powerLevel: 80,
    charges: 16,
  },
  {
    name: 'M01MC Shield',
    imageName: getImageName('AX_MC001'),
    filename: 'AX_MC001_smd',
    faction: factions.TAK,
  },
  {
    name: 'M02MC Bucker',
    imageName: getImageName('AX_MC002'),
    filename: 'AX_MC002',
    faction: factions.TAK,
  },
  {
    name: 'MSK-MC200',
    imageName: getImageName('AX_MC032'),
    filename: 'AX_MC032',
    faction: factions.MSK,
  },
  {
    name: 'RFZ-AMS-1',
    imageName: getImageName('AX_MC031'),
    filename: 'AX_MC031',
    faction: factions.MSK,
    isRaf: true,
  },
  {
    name: 'MSK-MC100',
    imageName: getImageName('AX_MC031'),
    filename: 'AX_MC031',
    faction: factions.MSK,
  }
]

export const partsRotorcraft: PartialPart<Rotorcraft>[] = [
  {
    name: 'RFZ-ARC-1',
    imageName: getImageName('AX_RC061'),
    filename: 'AX_RC061',
    faction: factions.SK,
    isRaf: true,
    weight: 185,
    energyUse: 11,
    durability: 2231,
    defKE: 20,
    defCE: 30,
    lift: 280,
    condenserUse: 676,
  },
  {
    name: 'RC-Sununu',
    imageName: getImageName('AX_RC061'),
    filename: 'AX_RC061',
    faction: factions.SK,
  },
  {
    name: 'RC-Nasr',
    imageName: getImageName('AX_RC062'),
    filename: 'AX_RC062',
    faction: factions.SK,
  },
  {
    name: 'RC-Saqr',
    imageName: getImageName('AX_RC063'),
    filename: 'AX_RC063',
    faction: factions.SK,
  },
  {
    name: 'M01RC Cayley',
    imageName: getImageName('AX_RC001'),
    filename: 'AX_RC001',
    faction: factions.TAK,
  },
  {
    name: 'RC-Tawus',
    imageName: getImageName('AX_RC064'),
    filename: 'AX_RC064',
    faction: factions.SK,
  },
  {
    name: 'M02RC Wright',
    imageName: getImageName('AX_RC002'),
    filename: 'AX_RC002',
    faction: factions.TAK,
  },
  {
    name: 'MSK-RC100',
    imageName: getImageName('AX_RC031'),
    filename: 'AX_RC031',
    faction: factions.MSK,
  }
]

export const partsHeatSink: PartialPart<HeatSink>[] = [
  {
    name: 'RD-Nahar',
    imageName: getImageName('AX_RD061'),
    filename: 'AX_RD061',
    faction: factions.SK,
    weight: 86,energyUse: 15,
    durability: 2136,
    defKE: 27,
    defCE: 22,
    heatDispersion: 300,
  },
  {
    name: 'M01RD Carnot',
    imageName: getImageName('AX_RD001'),
    filename: 'AX_RD001',
    faction: factions.TAK,
  },
  {
    name: 'RD-Buhayra',
    imageName: getImageName('AX_RD062'),
    filename: 'AX_RD062',
    faction: factions.SK,
  },
  {
    name: 'M02RD Kelvin',
    imageName: getImageName('AX_RD002'),
    filename: 'AX_RD002',
    faction: factions.TAK,
  },
  {
    name: 'RFZ-ARD-1',
    imageName: getImageName('AX_RD031'),
    filename: 'AX_RD031',
    faction: factions.MSK,
    isRaf: true,
  },
  {
    name: 'MSK-RD100',
    imageName: getImageName('AX_RD031'),
    filename: 'AX_RD031',
    faction: factions.MSK,
  },
  {
    name: 'MSK-RD110',
    imageName: getImageName('AX_RD032'),
    filename: 'AX_RD032',
    faction: factions.MSK,
  },
  {
    name: 'MSK-RD120',
    imageName: getImageName('AX_RD033'),
    filename: 'AX_RD033',
    faction: factions.MSK,
  }
]

export const partsFuelTank: PartialPart<FuelTank>[] = [
  {
    name: 'RFZ-AFS-1',
    imageName: getImageName('AX_FS061'),
    filename: 'AX_FS061',
    faction: factions.SK,
    isRaf: true,
    weight: 104,
    energyUse: 2,
    durability: 935,
    defKE: 9,
    defCE: 2,
    additionalFuel: 50,
  },
  {
    name: 'FS-Halib',
    imageName: getImageName('AX_FS061'),
    filename: 'AX_FS061',
    faction: factions.SK,
  },
  {
    name: 'FS-Zabadi',
    imageName: getImageName('AX_FS062'),
    filename: 'AX_FS062',
    faction: factions.SK,
  },
  {
    name: 'M01FS Boyle',
    imageName: getImageName('AX_FS001'),
    filename: 'AX_FS001',
    faction: factions.TAK,
  },
  {
    name: 'M02FS Charles',
    imageName: getImageName('AX_FS002'),
    filename: 'AX_FS002',
    faction: factions.TAK,
  },
  {
    name: 'MSK-FS100',
    imageName: getImageName('AX_FS031'),
    filename: 'AX_FS031',
    faction: factions.MSK,
  },
  {
    name: 'MSK-FS101',
    imageName: getImageName('AX_FS032'),
    filename: 'AX_FS032',
    faction: factions.MSK,
  }
]

export const partsArmor: PartialPart<Armor>[] = [
  {
    name: 'RFZ-AAM-3',
    imageName: getImageName('AX_AM061'),
    filename: 'AX_AM061',
    faction: factions.SK,
    isRaf: true,
    weight: 112,
    energyUse: 1,
    durability: 4252,
    defKE: 50,
    defCE: 30,
  },
  {
    name: 'AM-Dhahab',
    imageName: getImageName('AX_AM061'),
    filename: 'AX_AM061',
    faction: factions.SK,
  },
  {
    name: 'AM-Fidda',
    imageName: getImageName('AX_AM062'),
    filename: 'AX_AM062',
    faction: factions.SK,
  },
  {
    name: 'M01AM Gauntlet',
    imageName: getImageName('AX_AM001'),
    filename: 'AX_AM001',
    faction: factions.TAK,
  },
  {
    name: 'AM-Nuhas',
    imageName: getImageName('AX_AM063'),
    filename: 'AX_AM063',
    faction: factions.SK,
  },
  {
    name: 'M02AM Vambrance',
    imageName: getImageName('AX_AM002'),
    filename: 'AX_AM002',
    faction: factions.TAK,
  },
  {
    name: 'MSK-AM100',
    imageName: getImageName('AX_AM034'),
    filename: 'AX_AM034',
    faction: factions.MSK,
  },
  {
    name: 'RFZ-AAM-1',
    imageName: getImageName('AX_AM031'),
    filename: 'AX_AM031',
    faction: factions.MSK,
    isRaf: true,
  },
  {
    name: 'M04AM Couter',
    imageName: getImageName('AX_AM003'),
    filename: 'AX_AM003',
    faction: factions.TAK,
  },
  {
    name: 'MSK-AM110',
    imageName: getImageName('AX_AM031'),
    filename: 'AX_AM031',
    faction: factions.MSK,
  },
  {
    name: 'MSK-AM120',
    imageName: getImageName('AX_AM032'),
    filename: 'AX_AM032',
    faction: factions.MSK,
  },
  {
    name: 'MSK-AM130',
    imageName: getImageName('AX_AM033'),
    filename: 'AX_AM033',
    faction: factions.MSK,
  },
  {
    name: 'AM-Hadid',
    imageName: getImageName('AX_AM071'),
    filename: 'AX_AM071',
    faction: factions.SK,
  },
  {
    name: 'AM-Safih',
    imageName: getImageName('AX_AM072'),
    filename: 'AX_AM072',
    faction: factions.SK,
  },
  {
    name: 'M03AM Greave',
    imageName: getImageName('AX_AM011'),
    filename: 'AX_AM011',
    faction: factions.SK,
  },
  {
    name: 'MSK-AM1100',
    imageName: getImageName('AX_AM042'),
    filename: 'AX_AM042',
    faction: factions.MSK,
  },
  {
    name: 'RFZ-AAM-2',
    imageName: getImageName('AX_AM041'),
    filename: 'AX_AM041',
    faction: factions.MSK,
    isRaf: true,
  },
  {
    name: 'MSK-AM1000',
    imageName: getImageName('AX_AM041'),
    filename: 'AX_AM041',
    faction: factions.MSK,
  },
  {
    name: 'M05AM Poleyn',
    imageName: getImageName('AX_AM012'),
    filename: 'AX_AM012',
    faction: factions.TAK,
  },
  {
    name: 'MSK-AM1200',
    imageName: getImageName('AX_AM043'),
    filename: 'AX_AM043',
    faction: factions.MSK,
  },
]

export const partsNaMaker: PartialPart<NaMaker>[] = [
  {
    name: 'NM-Kawkab',
    imageName: getImageName('AX_NM064'),
    filename: 'AX_NM064',
    faction: factions.SK,
  },
  {
    name: 'RFZ-NM-3',
    imageName: getImageName('AX_NM064'),
    filename: 'AX_NM064',
    faction: factions.SK,
    isRaf: true,
  },
  {
    name: 'NM-Alkawn',
    imageName: getImageName('AX_NM061'),
    filename: 'AX_NM061',
    faction: factions.SK,
  },
  {
    name: 'NM-Ashshams',
    imageName: getImageName('AX_NM062'),
    filename: 'AX_NM062',
    faction: factions.SK,
  },
  {
    name: 'NM-Najm',
    imageName: getImageName('AX_NM063'),
    filename: 'AX_NM063',
    faction: factions.SK,
  },
  {
    name: 'M02NM Bell',
    imageName: getImageName('AX_NM002'),
    filename: 'AX_NM002',
    faction: factions.SK,
  },
  {
    name: 'RFZ-NM-1',
    imageName: getImageName('AX_NM001'),
    filename: 'AX_NM001',
    faction: factions.TAK,
    isRaf: true,
  },
  {
    name: 'M01NM Morse',
    imageName: getImageName('AX_NM001'),
    filename: 'AX_NM001',
    faction: factions.TAK,
  },
  {
    name: 'M03NM Hertz',
    imageName: getImageName('AX_NM003'),
    filename: 'AX_NM003',
    faction: factions.TAK,
  },
  {
    name: 'RFZ-NM-2',
    imageName: getImageName('AX_NM031'),
    filename: 'AX_NM031',
    faction: factions.MSK,
    isRaf: true,
  },
  {
    name: 'MSK-NM1000',
    imageName: getImageName('AX_NM031'),
    filename: 'AX_NM031',
    faction: factions.MSK,
  },
  {
    name: 'M04NM Maxwell',
    imageName: getImageName('AX_NM004'),
    filename: 'AX_NM004',
    faction: factions.TAK,
  },
  {
    name: 'MSK-NM1500',
    imageName: getImageName('AX_NM032'),
    filename: 'AX_NM032',
    faction: factions.MSK,
  },
  {
    name: 'MSK-NM2000',
    imageName: getImageName('AX_NM033'),
    filename: 'AX_NM033',
    faction: factions.MSK,
  },
  {
    name: 'MSK-NM2500',
    imageName: getImageName('AX_NM034'),
    filename: 'AX_NM034',
    faction: factions.MSK,
  },
]

export const partsLightArms: PartialPart<(Weapon | WeaponMultiAmmo)>[] = [
  // Machine Gun (8)
  {
    name: 'Mcg-Hajal',
    imageName: getImageName('WP_MG062'),
    filename: 'WP_MG062',
    faction: factions.SK,
    category: weaponCategories.MachineGun,
    weight: 164,
    energyUse: 20,
    durability: 1194,
    defKE: 26,
    defCE: 18,
    roundAmmoType: 'KE',
    penetrationPower: 252,
    weaponAmmoType: 'AP', // e.g. 'AP'
    range: 260,
    heatOfImpact: 47,
    cost: 1,
    fullAuto: 38,
    maxAmmo: 380,
    reloadTime: 400,
    scope: scopes.Normal,
  },
  {
    name: 'RFZ-WMG-3',
    imageName: getImageName('WP_MG002'),
    filename: 'WP_MG002',
    faction: factions.TAK,
    isRaf: true,
    category: weaponCategories.MachineGun,
  },
  {
    name: 'M07MG Dagger',
    imageName: getImageName('WP_MG002'),
    filename: 'WP_MG002',
    faction: factions.TAK,
    category: weaponCategories.MachineGun,
  },
  {
    name: 'RFZ-WMG-2',
    imageName: getImageName('WP_MG061'),
    filename: 'WP_MG061',
    faction: factions.SK,
    isRaf: true,
    category: weaponCategories.MachineGun,
    isHex: true,
  },
  {
    name: 'M18MG Stylet',
    imageName: getImageName('WP_MG001'),
    filename: 'WP_MG001',
    faction: factions.TAK,
    category: weaponCategories.MachineGun,
    isHex: true,
  },
  {
    name: 'Mcg-Hamama',
    imageName: getImageName('WP_MG061'),
    filename: 'WP_MG061',
    faction: factions.SK,
    category: weaponCategories.MachineGun,
    isHex: true,
  },
  {
    name: 'RFZ-WMG-1',
    imageName: getImageName('WP_MG031'),
    filename: 'WP_MG031',
    faction: factions.MSK,
    isRaf: true,
    category: weaponCategories.MachineGun,
    isHex: true,
  },
  {
    name: 'MSK-MG100',
    imageName: getImageName('WP_MG031'),
    filename: 'WP_MG031',
    faction: factions.MSK,
    category: weaponCategories.MachineGun,
    isHex: true,
  },

  // Grenade (7)
  {
    name: 'M30GL Axe',
    imageName: getImageName('WP_GL002'),
    filename: 'WP_GL002',
    faction: factions.TAK,
    category: weaponCategories.Grenade,
  },
  {
    name: 'M09GL Adze',
    imageName: getImageName('WP_GL001'),
    filename: 'WP_GL001',
    faction: factions.TAK,
    category: weaponCategories.Grenade,
  },
  {
    name: 'MSK-GL10',
    imageName: getImageName('WP_GL031'),
    filename: 'WP_GL031',
    faction: factions.MSK,
    category: weaponCategories.Grenade,
  },
  {
    name: 'RFZ-WGL-1',
    imageName: getImageName('WP_GL061'),
    filename: 'WP_GL061',
    faction: factions.SK,
    isRaf: true,
    category: weaponCategories.Grenade,
    isHex: true,
  },
  {
    name: 'Grl-Mushmis',
    imageName: getImageName('WP_GL061'),
    filename: 'WP_GL061',
    faction: factions.SK,
    category: weaponCategories.Grenade,
    isHex: true,
  },
  {
    name: 'Grl-Ghaim',
    imageName: getImageName('WP_GL062'),
    filename: 'WP_GL062',
    faction: factions.SK,
    category: weaponCategories.Grenade,
    isHex: true,
  },
  {
    name: 'Grl-Mumtir',
    imageName: getImageName('WP_GL063'),
    filename: 'WP_GL063',
    faction: factions.SK,
    category: weaponCategories.Grenade,
    isHex: true,
  },

  // HEAT Rocket (8)
  {
    name: 'HTR-Tamatim',
    imageName: getImageName('WP_CR063'),
    filename: 'WP_CR063',
    faction: factions.SK,
    category: weaponCategories.HeatRocket,
    isHex: true,
  },
  {
    name: 'RFZ-WHT-1',
    imageName: getImageName('WP_CR001'),
    filename: 'WP_CR001',
    faction: factions.TAK,
    isRaf: true,
    category: weaponCategories.HeatRocket,
  },
  {
    name: 'M33HT Partisan',
    imageName: getImageName('WP_CR002'),
    filename: 'WP_CR002',
    faction: factions.TAK,
    category: weaponCategories.HeatRocket,
  },
  {
    name: 'M09HT Spear',
    imageName: getImageName('WP_CR001'),
    filename: 'WP_CR001',
    faction: factions.TAK,
    category: weaponCategories.HeatRocket,
  },
  {
    name: 'MSK-HT10',
    imageName: getImageName('WP_CR031'),
    filename: 'WP_CR031',
    faction: factions.MSK,
    category: weaponCategories.HeatRocket,
  },
  {
    name: 'RFZ-WHT-2',
    imageName: getImageName('WP_CR061'),
    filename: 'WP_CR061',
    faction: factions.SK,
    isRaf: true,
    category: weaponCategories.HeatRocket,
    isHex: true,
  },
  {
    name: 'HTR-Jazar',
    imageName: getImageName('WP_CR061'),
    filename: 'WP_CR061',
    faction: factions.SK,
    category: weaponCategories.HeatRocket,
    isHex: true,
  },
  {
    name: 'HTR-Khiyar',
    imageName: getImageName('WP_CR062'),
    filename: 'WP_CR062',
    faction: factions.SK,
    category: weaponCategories.HeatRocket,
    isHex: true,
  },

  // Shotgun (8)
  {
    name: 'Stg-Burum',
    imageName: getImageName('WP_ST061'),
    filename: 'WP_ST061',
    faction: factions.SK,
    category: weaponCategories.Shotgun,
  },
  {
    name: 'RFZ-WSG-1',
    imageName: getImageName('WP_ST001'),
    filename: 'WP_ST001',
    faction: factions.TAK,
    isRaf: true,
    category: weaponCategories.Shotgun,
  },
  {
    name: 'MSK-SG101',
    imageName: getImageName('WP_ST033'),
    filename: 'WP_ST033',
    faction: factions.MSK,
    category: weaponCategories.Shotgun,
    isHex: true,
  },
  {
    name: 'RFZ-WSG-2',
    imageName: getImageName('WP_ST031'),
    filename: 'WP_ST031',
    faction: factions.MSK,
    isRaf: true,
    category: weaponCategories.Shotgun,
    isHex: true,
  },
  {
    name: 'M08SG Club',
    imageName: getImageName('WP_ST001'),
    filename: 'WP_ST001',
    faction: factions.TAK,
    category: weaponCategories.Shotgun,
  },
  {
    name: 'MSK-SG100',
    imageName: getImageName('WP_ST031'),
    filename: 'WP_ST031',
    faction: factions.MSK,
    category: weaponCategories.Shotgun,
    isHex: true,
  },
  {
    name: 'M24SG Mace',
    imageName: getImageName('WP_ST002'),
    filename: 'WP_ST002',
    faction: factions.TAK,
    category: weaponCategories.Shotgun,
  },
  {
    name: 'MSK-SG200/D',
    imageName: getImageName('WP_ST032'),
    filename: 'WP_ST032',
    faction: factions.MSK,
    category: weaponCategories.Shotgun,
    isHex: true,
  },

  // Assault Rifle (10)
  {
    name: 'AsR-Timsah',
    imageName: getImageName('WP_AR062'),
    filename: 'WP_AR062',
    faction: factions.SK,
    category: weaponCategories.AssaultRifle,
    isHex: true,
  },
  {
    name: 'RFZ-WAR-2',
    imageName: getImageName('WP_AR061'),
    filename: 'WP_AR061',
    faction: factions.SK,
    isRaf: true,
    category: weaponCategories.AssaultRifle,
    isHex: true,
  },
  {
    name: 'AsR-Thuban',
    imageName: getImageName('WP_AR061'),
    filename: 'WP_AR061',
    faction: factions.SK,
    category: weaponCategories.AssaultRifle,
    isHex: true,
  },
  {
    name: 'RFZ-WAR-1',
    imageName: getImageName('WP_AR001'),
    filename: 'WP_AR001',
    faction: factions.TAK,
    isRaf: true,
    category: weaponCategories.AssaultRifle,
    isHex: true,
  },
  {
    name: 'RFZ-WAR-3',
    imageName: getImageName('WP_AR031'),
    filename: 'WP_AR031',
    faction: factions.MSK,
    isRaf: true,
    category: weaponCategories.AssaultRifle,
    isHex: true,
  },
  {
    name: 'M06AR Baselard',
    imageName: getImageName('WP_AR001'),
    filename: 'WP_AR001',
    faction: factions.TAK,
    category: weaponCategories.AssaultRifle,
    isHex: true,
  },
  {
    name: 'M19AR Cutlass',
    imageName: getImageName('WP_AR002'),
    filename: 'WP_AR002',
    faction: factions.TAK,
    category: weaponCategories.AssaultRifle,
    isHex: true,
  },
  {
    name: 'MSK-AR100',
    imageName: getImageName('WP_AR031'),
    filename: 'WP_AR031',
    faction: factions.MSK,
    category: weaponCategories.AssaultRifle,
    isHex: true,
  },
  {
    name: 'MSK-AR200',
    imageName: getImageName('WP_AR032'),
    filename: 'WP_AR032',
    faction: factions.MSK,
    category: weaponCategories.AssaultRifle,
    isHex: true,
  },
  {
    name: 'M34AR Hanger',
    imageName: getImageName('WP_AR003'),
    filename: 'WP_AR003',
    faction: factions.TAK,
    category: weaponCategories.AssaultRifle,
    isHex: true,
  },

  // Sniper Rifle (9)
  {
    name: 'SpR-Aruzz',
    imageName: getImageName('WP_SR061'),
    filename: 'WP_SR061',
    faction: factions.SK,
    category: weaponCategories.SniperRifle,
  },
  {
    name: 'SpR-Ruzz',
    imageName: getImageName('WP_SR062'),
    filename: 'WP_SR062',
    faction: factions.SK,
    category: weaponCategories.SniperRifle,
  },
  {
    name: 'RFZ-WSR-1',
    imageName: getImageName('WP_SR001'),
    filename: 'WP_SR001',
    faction: factions.TAK,
    isRaf: true,
    category: weaponCategories.SniperRifle,
    isHex: true,
  },
  {
    name: 'M05SR Estoc',
    imageName: getImageName('WP_SR001'),
    filename: 'WP_SR001',
    faction: factions.TAK,
    category: weaponCategories.SniperRifle,
    isHex: true,
  },
  {
    name: 'M17Sr Tuck',
    imageName: getImageName('WP_SR002'),
    filename: 'WP_SR002',
    faction: factions.TAK,
    category: weaponCategories.SniperRifle,
    isHex: true,
  },
  {
    name: 'M35SR Rapir',
    imageName: getImageName('WP_SR003'),
    filename: 'WP_SR003',
    faction: factions.TAK,
    category: weaponCategories.SniperRifle,
    isHex: true,
  },
  {
    name: 'RFZ-WSR-2',
    imageName: getImageName('WP_SR031'),
    filename: 'WP_SR031',
    faction: factions.MSK,
    isRaf: true,
    category: weaponCategories.SniperRifle,
    isHex: true,
  },
  {
    name: 'MSK-SR200',
    imageName: getImageName('WP_SR032'),
    filename: 'WP_SR032',
    faction: factions.MSK,
    category: weaponCategories.SniperRifle,
    isHex: true,
  },
  {
    name: 'MSK-SR100',
    imageName: getImageName('WP_SR031'),
    filename: 'WP_SR031',
    faction: factions.MSK,
    category: weaponCategories.SniperRifle,
    isHex: true,
  },

  // Sniper Cannon (7)
  {
    name: 'M36SC Sabre',
    imageName: getImageName('WP_SG003'),
    filename: 'WP_SG003',
    faction: factions.TAK,
    category: weaponCategories.SniperCannon,
    isHex: true,
  },
  {
    name: 'SpC-Himmis',
    imageName: getImageName('WP_SG061'),
    filename: 'WP_SG061',
    faction: factions.SK,
    category: weaponCategories.SniperCannon,
    isHex: true,
  },
  {
    name: 'RFZ-WSC-1',
    imageName: getImageName('WP_SG001'),
    filename: 'WP_SG001',
    faction: factions.TAK,
    isRaf: true,
    category: weaponCategories.SniperCannon,
    isHex: true,
  },
  {
    name: 'M04SC Epee',
    imageName: getImageName('WP_SG001'),
    filename: 'WP_SG001',
    faction: factions.TAK,
    category: weaponCategories.SniperCannon,
    isHex: true,
  },
  {
    name: 'M22SC Fleuret',
    imageName: getImageName('WP_SG002'),
    filename: 'WP_SG002',
    faction: factions.TAK,
    category: weaponCategories.SniperCannon,
    isHex: true,
  },
  {
    name: 'MSK-SC100',
    imageName: getImageName('WP_SG031'),
    filename: 'WP_SG031',
    faction: factions.MSK,
    category: weaponCategories.SniperCannon,
    isHex: true,
  },
  {
    name: 'MSK-SC200',
    imageName: getImageName('WP_SG032'),
    filename: 'WP_SG032',
    faction: factions.MSK,
    category: weaponCategories.SniperCannon,
    isHex: true,
  },

  // Rocket (7)
  {
    name: 'RFZ-WRL-2',
    imageName: getImageName('WP_RL061'),
    filename: 'WP_RL061',
    faction: factions.SK,
    isRaf: true,
    category: weaponCategories.Rocket,
    isHex: true,
  },
  {
    name: 'Rtl-Khass',
    imageName: getImageName('WP_RL061'),
    filename: 'WP_RL061',
    faction: factions.SK,
    category: weaponCategories.Rocket,
    isHex: true,
  },
  {
    name: 'Rtl-Kurunb',
    imageName: getImageName('WP_RL062'),
    filename: 'WP_RL062',
    faction: factions.SK,
    category: weaponCategories.Rocket,
    isHex: true,
  },
  {
    name: 'MSK-RL200',
    imageName: getImageName('WP_RL034'),
    filename: 'WP_RL034',
    faction: factions.MSK,
    category: weaponCategories.Rocket,
    isHex: true,
  },
  {
    name: 'RFZ-WRL-1',
    imageName: getImageName('WP_RL033'),
    filename: 'WP_RL033',
    faction: factions.MSK,
    category: weaponCategories.Rocket,
    isHex: true,
  },
  {
    name: 'M13RL Halberd',
    imageName: getImageName('WP_RL002'),
    filename: 'WP_RL002',
    faction: factions.TAK,
    category: weaponCategories.Rocket,
    isHex: true,
  },
  {
    name: 'MSK-RL100',
    imageName: getImageName('WP_RL033'),
    filename: 'WP_RL033',
    faction: factions.MSK,
    category: weaponCategories.Rocket,
    isHex: true,
  },

  // Cannon (11)
  {
    name: 'Cnn-Bisilla',
    imageName: getImageName('WP_GN062'),
    filename: 'WP_GN062',
    faction: factions.SK,
    category: weaponCategories.Cannon,
    isHex: true,
  },
  {
    name: 'RFZ-WCN-2',
    imageName: getImageName('WP_GN031'),
    filename: 'WP_GN031',
    faction: factions.MSK,
    isRaf: true,
    category: weaponCategories.Cannon,
    isHex: true,
  },
  {
    name: 'Cnn-Fasuliya',
    imageName: getImageName('WP_GN061'),
    filename: 'WP_GN061',
    faction: factions.SK,
    category: weaponCategories.Cannon,
    isHex: true,
  },
  {
    name: 'MSK-CN100',
    imageName: getImageName('WP_GN031'),
    filename: 'WP_GN031',
    faction: factions.MSK,
    category: weaponCategories.Cannon,
    isHex: true,
  },
  {
    name: 'RFZ-WCN-1',
    imageName: getImageName('WP_GN001'),
    filename: 'WP_GN001',
    faction: factions.TAK,
    isRaf: true,
    category: weaponCategories.Cannon,
    isHex: true,
  },
  {
    name: 'M20CN Anelace',
    imageName: getImageName('WP_GN002'),
    filename: 'WP_GN002',
    faction: factions.TAK,
    category: weaponCategories.Cannon,
    isHex: true,
  },
  {
    name: 'M01CN Falchion',
    imageName: getImageName('WP_GN001'),
    filename: 'WP_GN001',
    faction: factions.TAK,
    category: weaponCategories.Cannon,
    isHex: true,
  },
  {
    name: 'MSK-CN201',
    imageName: getImageName('WP_GN033'),
    filename: 'WP_GN033',
    faction: factions.MSK,
    category: weaponCategories.Cannon,
    isHex: true,
  },
  {
    name: 'M27CN Flanberg',
    imageName: getImageName('WP_GN003'),
    filename: 'WP_GN003',
    faction: factions.TAK,
    category: weaponCategories.Cannon,
    isHex: true,
  },
  {
    name: 'MSK-CN200',
    imageName: getImageName('WP_GN032'),
    filename: 'WP_GN032',
    faction: factions.MSK,
    category: weaponCategories.Cannon,
    isHex: true,
  },
  {
    name: 'MSK-CN300',
    imageName: getImageName('WP_GN034'),
    filename: 'WP_GN034',
    faction: factions.MSK,
    category: weaponCategories.Cannon,
    isHex: true,
  },

  // Howitzer (11)
  {
    name: 'RFZ-WHW-2',
    imageName: getImageName('WP_HW061'),
    filename: 'WP_HW061',
    faction: factions.SK,
    isRaf: true,
    category: weaponCategories.Howitzer,
    isHex: true,
  },
  {
    name: 'Hwz-Matar',
    imageName: getImageName('WP_HW061'),
    filename: 'WP_HW061',
    faction: factions.SK,
    category: weaponCategories.Howitzer,
    isHex: true,
  },
  {
    name: 'RFZ-WHW-1',
    imageName: getImageName('WP_HW001'),
    filename: 'WP_HW001',
    faction: factions.TAK,
    isRaf: true,
    category: weaponCategories.Howitzer,
    isHex: true,
  },
  {
    name: 'M02HW Espadon',
    imageName: getImageName('WP_HW001'),
    filename: 'WP_HW001',
    faction: factions.TAK,
    category: weaponCategories.Howitzer,
    isHex: true,
  },
  {
    name: 'Hwz-Thalj',
    imageName: getImageName('WP_HW062'),
    filename: 'WP_HW062',
    faction: factions.SK,
    category: weaponCategories.Howitzer,
    isHex: true,
  },
  {
    name: 'M21HW Faus',
    imageName: getImageName('WP_HW002'),
    filename: 'WP_HW002',
    faction: factions.TAK,
    category: weaponCategories.Howitzer,
    isHex: true,
  },
  {
    name: 'Hwz-Ghayma',
    imageName: getImageName('WP_HW063'),
    filename: 'WP_HW063',
    faction: factions.SK,
    category: weaponCategories.Howitzer,
    isHex: true,
  },
  {
    name: 'M28HW Pallasch',
    imageName: getImageName('WP_HW003'),
    filename: 'WP_HW003',
    faction: factions.TAK,
    category: weaponCategories.Howitzer,
    isHex: true,
  },
  {
    name: 'MSK-HW300',
    imageName: getImageName('WP_HW033'),
    filename: 'WP_HW033',
    faction: factions.MSK,
    category: weaponCategories.Howitzer,
    isHex: true,
  },
  {
    name: 'MSK-HW100',
    imageName: getImageName('WP_HW031'),
    filename: 'WP_HW031',
    faction: factions.MSK,
    category: weaponCategories.Howitzer,
    isHex: true,
  },
  {
    name: 'MSK-HW200',
    imageName: getImageName('WP_HW032'),
    filename: 'WP_HW032',
    faction: factions.MSK,
    category: weaponCategories.Howitzer,
    isHex: true,
  },

  // Mortar (11)
  {
    name: 'RFZ-WMT-1',
    imageName: getImageName('WP_MT001'),
    filename: 'WP_MT001',
    faction: factions.TAK,
    isRaf: true,
    category: weaponCategories.Mortar,
  },
  {
    name: 'Mtr-Qamh',
    imageName: getImageName('WP_MT061'),
    filename: 'WP_MT061',
    faction: factions.SK,
    category: weaponCategories.Mortar,
  },
  {
    name: 'M03MT Dusack',
    imageName: getImageName('WP_MT001'),
    filename: 'WP_MT001',
    faction: factions.TAK,
    category: weaponCategories.Mortar,
  },
  {
    name: 'MSK-MT10',
    imageName: getImageName('WP_MT031'),
    filename: 'WP_MT031',
    faction: factions.MSK,
    category: weaponCategories.Mortar,
  },
  {
    name: 'RFZ-WMT-3',
    imageName: getImageName('WP_MT062'),
    filename: 'WP_MT062',
    faction: factions.SK,
    isRaf: true,
    category: weaponCategories.Mortar,
  },
  {
    name: 'RFZ-WMT-2',
    imageName: getImageName('WP_MT032'),
    filename: 'WP_MT032',
    faction: factions.MSK,
    isRaf: true,
    category: weaponCategories.Mortar,
  },
  {
    name: 'Mtr-Hinta',
    imageName: getImageName('WP_MT062'),
    filename: 'WP_MT062',
    faction: factions.SK,
    category: weaponCategories.Mortar,
  },
  {
    name: 'MSK-MT20',
    imageName: getImageName('WP_MT032'),
    filename: 'WP_MT032',
    faction: factions.MSK,
    category: weaponCategories.Mortar,
  },
  {
    name: 'Mtr-Shair',
    imageName: getImageName('WP_MT063'),
    filename: 'WP_MT063',
    faction: factions.SK,
    category: weaponCategories.Mortar,
  },
  {
    name: 'M31MT Falcata',
    imageName: getImageName('WP_MT002'),
    filename: 'WP_MT002',
    faction: factions.TAK,
    category: weaponCategories.Mortar,
  },
  {
    name: 'MSK-MT21',
    imageName: getImageName('WP_MT033'),
    filename: 'WP_MT033',
    faction: factions.MSK,
    category: weaponCategories.Mortar,
  },

  // Anti HOUND Pile (7)
  {
    name: 'AHP-Lihya',
    imageName: getImageName('WP_CP063'),
    filename: 'WP_CP063',
    faction: factions.SK,
    category: weaponCategories.AntiHoundPile,
    isHex: true,
  },
  {
    name: 'AHP-Sharib',
    imageName: getImageName('WP_CP062'),
    filename: 'WP_CP062',
    faction: factions.SK,
    category: weaponCategories.AntiHoundPile,
    isHex: true,
  },
  {
    name: 'M10HP Lance',
    imageName: getImageName('WP_CP001'),
    filename: 'WP_CP001',
    faction: factions.TAK,
    category: weaponCategories.AntiHoundPile,
    isHex: true,
  },
  {
    name: 'M23HP Ballista',
    imageName: getImageName('WP_CP002'),
    filename: 'WP_CP002',
    faction: factions.TAK,
    category: weaponCategories.AntiHoundPile,
    isHex: true,
  },
  {
    name: 'RFZ-WHP-1',
    imageName: getImageName('WP_CP061'),
    filename: 'WP_CP061',
    faction: factions.SK,
    isRaf: true,
    category: weaponCategories.AntiHoundPile,
    isHex: true,
  },
  {
    name: 'AHP-Ras',
    imageName: getImageName('WP_CP061'),
    filename: 'WP_CP061',
    faction: factions.SK,
    category: weaponCategories.AntiHoundPile,
    isHex: true,
  },
  {
    name: 'MSK-HP100',
    imageName: getImageName('WP_CP031'),
    filename: 'WP_CP031',
    faction: factions.MSK,
    category: weaponCategories.AntiHoundPile,
    isHex: true,
  },

  // Land Mine (8)
  {
    name: 'LdM-Lahm',
    imageName: getImageName('WP_LM063'),
    filename: 'WP_LM063',
    faction: factions.SK,
    category: weaponCategories.LandMine,
    isHex: true,
  },
  {
    name: 'RFZ-WLM-1',
    imageName: getImageName('WP_LM031'),
    filename: 'WP_LM031',
    faction: factions.MSK,
    isRaf: true,
    category: weaponCategories.LandMine,
    isHex: true,
  },
  {
    name: 'RFZ-WLM-2',
    imageName: getImageName('WP_LM031'),
    filename: 'WP_LM031',
    faction: factions.SK,
    isRaf: true,
    category: weaponCategories.LandMine,
    isHex: true,
  },
  {
    name: 'M11LM Claymore',
    imageName: getImageName('WP_LM001'),
    filename: 'WP_LM001',
    faction: factions.TAK,
    category: weaponCategories.LandMine,
    isHex: true,
  },
  {
    name: 'LdM-Zinifa',
    imageName: getImageName('WP_LM062'),
    filename: 'WP_LM062',
    faction: factions.SK,
    category: weaponCategories.LandMine,
    isHex: true,
  },
  {
    name: 'MSK-LM100',
    imageName: getImageName('WP_LM031'),
    filename: 'WP_LM031',
    faction: factions.MSK,
    category: weaponCategories.LandMine,
    isHex: true,
  },
  {
    name: 'LdM-Harshafa',
    imageName: getImageName('WP_LM061'),
    filename: 'WP_LM061',
    faction: factions.SK,
    category: weaponCategories.LandMine,
    isHex: true,
  },
  {
    name: 'MSK-LM200',
    imageName: getImageName('WP_LM032'),
    filename: 'WP_LM032',
    faction: factions.MSK,
    category: weaponCategories.LandMine,
    isHex: true,
  },

  // Bomb Dispenser (9)
  {
    name: 'RFZ-WBD-1',
    imageName: getImageName('WP_CB001'),
    filename: 'WP_CB001',
    faction: factions.TAK,
    isRaf: true,
    category: weaponCategories.BombDispenser,
    isHex: true,
  },
  {
    name: 'BmD-Samakumusa',
    imageName: getImageName('WP_CB063'),
    filename: 'WP_CB063',
    faction: factions.SK,
    category: weaponCategories.BombDispenser,
    isHex: true,
  },
  {
    name: 'M12BD Gladius',
    imageName: getImageName('WP_CB001'),
    filename: 'WP_CB001',
    faction: factions.TAK,
    category: weaponCategories.BombDispenser,
    isHex: true,
  },
  {
    name: 'M23BD Walloon',
    imageName: getImageName('WP_CB002'),
    filename: 'WP_CB002',
    faction: factions.TAK,
    category: weaponCategories.BombDispenser,
    isHex: true,
  },
  {
    name: 'RFZ-WBD-2',
    imageName: getImageName('WP_CB061'),
    filename: 'WP_CB061',
    faction: factions.SK,
    isRaf: true,
    category: weaponCategories.BombDispenser,
    isHex: true,
  },
  {
    name: 'BmD-Sadaf',
    imageName: getImageName('WP_CB064'),
    filename: 'WP_CB064',
    faction: factions.SK,
    category: weaponCategories.BombDispenser,
    isHex: true,
  },
  {
    name: 'BmD-Sardin',
    imageName: getImageName('WP_CB061'),
    filename: 'WP_CB061',
    faction: factions.SK,
    category: weaponCategories.BombDispenser,
    isHex: true,
  },
  {
    name: 'BmD-Salmun',
    imageName: getImageName('WP_CB062'),
    filename: 'WP_CB062',
    faction: factions.SK,
    category: weaponCategories.BombDispenser,
    isHex: true,
  },
  {
    name: 'MSK-BD100',
    imageName: getImageName('WP_CB031'),
    filename: 'WP_CB031',
    faction: factions.MSK,
    category: weaponCategories.BombDispenser,
    isHex: true,
  },
]

export const partsHeavyArms: PartialPart<(Weapon | WeaponMultiAmmo)>[] = [
  // Huge Rocket (6)
  {
    name: 'HRl-Basal',
    imageName: getImageName('WH_LR061'),
    filename: 'WH_LR061',
    faction: factions.SK,
    category: weaponCategories.HugeRocket,
  },
  {
    name: 'M29HR Trident',
    imageName: getImageName('WH_LR002'),
    filename: 'WH_LR002',
    faction: factions.TAK,
    category: weaponCategories.HugeRocket,
  },
  {
    name: 'RFZ-WHR-1',
    imageName: getImageName('WH_LR001'),
    filename: 'WH_LR001',
    faction: factions.TAK,
    isRaf: true,
    category: weaponCategories.HugeRocket,
  },
  {
    name: 'M15HR Guisarme',
    imageName: getImageName('WH_LR001'),
    filename: 'WH_LR001',
    faction: factions.TAK,
    category: weaponCategories.HugeRocket,
  },
  {
    name: 'MSK-HR1000',
    imageName: getImageName('WH_LR031'),
    filename: 'WH_LR031',
    faction: factions.MSK,
    category: weaponCategories.HugeRocket,
  },
  {
    name: 'MSK-HR1001',
    imageName: getImageName('WH_LR032'),
    filename: 'WH_LR032',
    faction: factions.MSK,
    category: weaponCategories.HugeRocket,
  },

  // Missile (8)
  {
    name: 'Msl-Khadrawat',
    imageName: getImageName('WH_MS061'),
    filename: 'WH_MS061',
    faction: factions.SK,
    category: weaponCategories.Missile,
  },
  {
    name: 'M14MS Javelin',
    imageName: getImageName('WH_MS001'),
    filename: 'WH_MS001',
    faction: factions.TAK,
    category: weaponCategories.Missile,
  },
  {
    name: 'M26MS Tomahawk',
    imageName: getImageName('WH_MS002'),
    filename: 'WH_MS002',
    faction: factions.TAK,
    category: weaponCategories.Missile,
  },

  {
    name: 'MSK-MS1000',
    imageName: getImageName('WH_MS031'),
    filename: 'WH_MS031',
    faction: factions.MSK,
    category: weaponCategories.Missile,
  },
  {
    name: 'RFZ-WMS-1',
    imageName: getImageName('WH_MS031'),
    filename: 'WH_MS031',
    faction: factions.MSK,
    isRaf: true,
    category: weaponCategories.Missile,
  },
  {
    name: 'MSK-MS1500',
    imageName: getImageName('WH_MS032'),
    filename: 'WH_MS032',
    faction: factions.MSK,
    category: weaponCategories.Missile,
  },
  {
    name: 'MSK-MS1501',
    imageName: getImageName('WH_MS034'),
    filename: 'WH_MS034',
    faction: factions.MSK,
    category: weaponCategories.Missile,
  },
  {
    name: 'MSK-MS1001',
    imageName: getImageName('WH_MS033'),
    filename: 'WH_MS033',
    faction: factions.MSK,
    category: weaponCategories.Missile,
  },

  // Huge Cannon (8)
  {
    name: 'MCn-Asifa',
    imageName: getImageName('WH_HC061'),
    filename: 'WH_HC061',
    faction: factions.SK,
    category: weaponCategories.HugeCannon,
  },
  {
    name: 'M16HC Bastard',
    imageName: getImageName('WH_HC001'),
    filename: 'WH_HC001',
    faction: factions.TAK,
    category: weaponCategories.HugeCannon,
  },
  {
    name: 'RFZ-WHC-1',
    imageName: getImageName('WH_HC031'),
    filename: 'WH_HC031',
    faction: factions.MSK,
    category: weaponCategories.HugeCannon,
  },
  {
    name: 'M25HC Gram',
    imageName: getImageName('WH_HC002'),
    filename: 'WH_HC002',
    faction: factions.TAK,
    category: weaponCategories.HugeCannon,
  },
  {
    name: 'MSK-HC1000/O',
    imageName: getImageName('WH_HC031'),
    filename: 'WH_HC031',
    faction: factions.MSK,
    category: weaponCategories.HugeCannon,
  },
  {
    name: 'MSK-HC1001/O',
    imageName: getImageName('WH_HC032'),
    filename: 'WH_HC032',
    faction: factions.MSK,
    category: weaponCategories.HugeCannon,
  },
  {
    name: 'MSK-HC1500/D',
    imageName: getImageName('WH_HC033'),
    filename: 'WH_HC033',
    faction: factions.MSK,
    category: weaponCategories.HugeCannon,
  },
  {
    name: 'MSK-HC1501/D',
    imageName: getImageName('WH_HC034'),
    filename: 'WH_HC034',
    faction: factions.MSK,
    category: weaponCategories.HugeCannon,
  },
]

/*
  {
    name: '',
    imageName: getImageName(''),
    filename: '',
    faction: factions.,
    category: weaponCategories.,
  },


  {
    name: '',
    imageName: getImageName(''),
    filename: '',
    faction: factions.,
  },
*/